name: Feature Request
description: Suggest an idea or enhancement for QRCrypt
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: "I would like QRCrypt to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Encryption/Security
        - QR Code Generation
        - Shamir Secret Sharing
        - Card Generation/Printing
        - Command Line Interface
        - File I/O
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: "In my workflow, I need to..."
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request

  - type: checkboxes
    id: considerations
    attributes:
      label: Considerations
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this feature hasn't been requested before
          required: true
        - label: This feature request is related to QRCrypt's core functionality (crypto wallet backup security)
          required: true